src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 * @UniqueEntity("email")

 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=191)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=191, unique=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="contacts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/ContactController.php
<?php


namespace App\Controller;


use App\Entity\Contact;
use App\Repository\ContactRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ContactController extends AbstractController
{
    /**
     * @IsGranted("ROLE_USER")
     * @param \App\Repository\ContactRepository $contactRepository
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     */
    public function index(ContactRepository $contactRepository)
    {
        return $this->render('contact/index.html.twig', [
            'contacts' => $contactRepository->findBy([
                'user' => $this->getUser(),
            ]),
        ]);
    }

    /**
     * @param \App\Entity\Contact $contact
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(Contact $contact)
    {
        $this->denyAccessUnlessGranted('VIEW', $contact);

        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function create()
    {
        return $this->render('contact/create.html.twig', [
            'contact' => new Contact(),
            'errors' => [],
        ]);
    }

    /**
     * @param \App\Entity\Contact $contact
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function edit(Contact $contact)
    {
        $this->denyAccessUnlessGranted('UPDATE', $contact);

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'errors' => [],
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @param \Symfony\Component\HttpFoundation\Request                 $request
     *
     * @param \Symfony\Component\Validator\Validator\ValidatorInterface $validator
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse| \Symfony\Component\HttpFoundation\Response
     */
    public function store(Request $request, ValidatorInterface $validator)
    {
        $contact = new Contact();
        $contact->setName($request->get('name'));
        $contact->setEmail($request->get('email'));
        $contact->setPhoneNumber($request->get('phone_number'));
        $errors = $validator->validate($contact);

        if (count($errors) > 0) {
            return $this->render('contact/create.html.twig', [
                'errors' => $errors,
                'contact' => $contact,
            ]);
        }
        $contact->setUser($this->getUser());
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($contact);
        $entityManager->flush();

        $this->addFlash('message', 'Contact successfully created');

        return $this->redirectToRoute('show_contact', [
            'id' => $contact->getId(),
        ]);
    }

    /**
     * @param \App\Entity\Contact                                       $contact
     *
     * @param \Symfony\Component\HttpFoundation\Request                 $request
     *
     * @param \Symfony\Component\Validator\Validator\ValidatorInterface $validator
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function update(Contact $contact, Request $request, ValidatorInterface $validator)
    {
        $this->denyAccessUnlessGranted('UPDATE', $contact);

        $contact->setName($request->get('name'));
        $contact->setEmail($request->get('email'));
        $contact->setPhoneNumber($request->get('phone_number'));

        $errors = $validator->validate($contact);
        if (count($errors) > 0) {
            return $this->render('contact/edit.html.twig', [
                'errors' => $errors,
                'contact' => $contact,
            ]);
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($contact);
        $entityManager->flush();

        $this->addFlash('message', 'Contact successfully updated');

        return $this->redirectToRoute('show_contact', [
            'id' => $contact->getId(),
        ]);
    }

    /**
     * @param \App\Entity\Contact $contact
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function destroy(Contact $contact)
    {
        $this->denyAccessUnlessGranted('DELETE', $contact);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($contact);
        $entityManager->flush();

        $this->addFlash('message', 'Contact successfully deleted');

        return $this->redirectToRoute('index_contact');
    }

}

templates/contact/create.html.twig
{% extends 'base.html.twig' %}
{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('index_contact') }}">Contacts</a>
    </li>
    <li class="breadcrumb-item active">Create New contact</li>
{% endblock %}

{% block body %}
    <h3>Create New Contact</h3>
    {% if(errors|length > 0) %}
        <ul class="list-group">
            {% for error in errors %}
                <li class="list-group-item list-group-item-danger"><b>{{ error.propertyPath }}</b> - {{ error.message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{{ path('save_contact') }}" method="post">
        <div class="form-group">
            <label>Full Name</label>
            <input type="text" class="form-control" name="name" value="{{ contact.name }}" required
                   placeholder="e.g. John Doe">
        </div>
        <div class="form-group">
            <label>Email Address</label>
            <input type="email" class="form-control" name="email" value="{{ contact.email }}" required
                   placeholder="e.g. johdoe@example.com">
        </div>
        <div class="form-group">
            <label>Phone Number</label>
            <input type="text" class="form-control" name="phone_number" value="{{ contact.phoneNumber }}"
                   placeholder="e.g. +880 123 4578 7895">
        </div>
        <div class="form-group text-right">
            <input type="submit" value="Save" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('index_contact') }}"> Contacts </a>
    </li>
    <li class="breadcrumb-item ">
        <a href="{{ path('show_contact',{id : contact.id }) }}"> {{ contact.name }}
        </a>
    </li>
    <li class="breadcrumb-item active">
        Edit
    </li>
{% endblock %}

{% block body %}
    <h3>Update {{ contact.getName() }}</h3>
    {% if(errors|length > 0) %}
        <ul class="list-group">
            {% for error in errors %}
                <li class="list-group-item list-group-item-danger"><b>{{ error.propertyPath }}</b> - {{ error.message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{{ path('update_contact',{id : contact.id}) }}" method="post">
        <input type="hidden" name="_method" value="PUT">
        <div class="form-group">
            <label>Full Name</label>
            <input type="text" class="form-control" name="name" value="{{ contact.name }}" required
                   placeholder="e.g. John Doe">
        </div>
        <div class="form-group">
            <label>Email Address</label>
            <input type="email" class="form-control" name="email" value="{{ contact.email }}" required
                   placeholder="e.g. johdoe@example.com">
        </div>
        <div class="form-group">
            <label>Phone Number</label>
            <input type="text" class="form-control" name="phone_number" value="{{ contact.phoneNumber }}"
                   placeholder="e.g. +880 123 4578 7895">
        </div>
        <div class="form-group text-right">
            <input type="submit" value="Save" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block breadcrumb %}
    <li class="breadcrumb-item">Contacts</li>
{% endblock %}

{% block body %}
    <table class="table table-responsive table-striped table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <td>&nbsp;</td>
        </tr>
        </thead>
        <tbody>
        {% for contact in contacts %}
            <tr>
                <td><a href="{{ path('show_contact',{id:contact.id}) }}">{{ contact.id }}</a></td>
                <td>{{ contact.name }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.phoneNumber }}</td>
                <td>
                    <a href="{{ path('edit_contact',{id: contact.id}) }}">Edit</a>
                    <form action="{{ path('destroy_contact',{id: contact.id}) }}" method="post"
                          onsubmit="return confirm('Are you sure you want to delete this record?')">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="submit" value="Delete" class="btn btn-outline-danger">
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('create_contact') }}">Create new Contact</a>
{% endblock %}

templates/contact/show.html.twig
{% extends 'base.html.twig' %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('index_contact') }}"> Contacts </a>
    </li>
    <li class="breadcrumb-item active">
        {{ contact.name }}
    </li>
{% endblock %}

{% block body %}
    <ul class="list-group text-center">
        <li class="list-group-item">Name : {{ contact.name }}</li>
        <li class="list-group-item">Email: {{ contact.email }}</li>
        <li class="list-group-item"> Phone Number: {{ contact.phoneNumber }}</li>
    </ul>
    <h3></h3>
{% endblock %}